openapi: 3.0.0
info:
  title: notification-service
  description: notification-service
  version: v1
servers:
  - url: http://localhost:8080/api/v1

paths:
  /payment:
    post:
      summary: сохранить список платежей
      tags:
        - payment
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Payment"

      responses:
        '201':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Payment"
        '500':
          "$ref": "#/components/responses/BadRequest"
        '403':
          "$ref": "#/components/responses/Forbidden"

  /total/sender/{id}:
    get:
      summary: сохранить список платежей
      tags:
        - total sum
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: long
          description: ID отправителя
      responses:
        '201':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TotalSum"
        '500':
          "$ref": "#/components/responses/BadRequest"
        '403':
          "$ref": "#/components/responses/Forbidden"


components:
  schemas:
    Payment:
      description: платёж
      type: object
      properties:
        sender:
          nullable: false
          type: long
          description: id отправителя
        receiver:
          nullable: false
          type: long
          description: id отправителя
        price:
          nullable: false
          type: long
          description: id отправителя

    TotalSum:
      description: платёж
      type: object
      properties:
        totalSum:
          nullable: false
          type: long
          description: общая сумма платежей отправителя

    Error:
      description: Ошибка
      title: Error
      type: object
      properties:
        code:
          description: Числовой код ошибки
          type: integer
          default: 400
        error:
          description: Класс ошибки
          type: string
        error_description:
          description: Сообщение, раскрывающее причину возникновения ошибки или любая другая информация
          type: string


  responses:
    BadRequest:
      description: Неверные параметры запроса
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Error"


    Forbidden:
      description: Нет прав на выполнение действия
      content:
        application/json:
          schema:
            "$ref": "#/components/schemas/Error"
