version: '3.3'

services:
  pg-payments-0:
    image: postgres:10.5
    env_file:
      - environment.env
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    entrypoint:
      bash -c "
      echo pg-start
      && docker-entrypoint.sh postgres
      "
  pg-payments-1:
    image: postgres:10.5
    env_file:
      - environment.env
    ports:
      - 5433:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    entrypoint:
      bash -c "
      echo pg-start
      && docker-entrypoint.sh postgres
      "

  pg-payments-2:
    image: postgres:10.5
    env_file:
      - environment.env
    ports:
      - 5434:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    entrypoint:
      bash -c "
      echo pg-start
      && docker-entrypoint.sh postgres
      "

  pg-payment-3:
    image: postgres:10.5
    env_file:
      - environment.env
    ports:
      - 5435:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    entrypoint:
      bash -c "
      echo pg-start
      && docker-entrypoint.sh postgres
      "

  pg-payment-4:
    image: postgres:10.5
    env_file:
      - environment.env
    ports:
      - 5436:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    entrypoint:
      bash -c "
      echo pg-start
      && docker-entrypoint.sh postgres
      "

  pg-3:
    image: postgres:10.5
    env_file:
      - environment.env
    ports:
      - 8432:5432
    volumes:
      - ./association_db:/docker-entrypoint-initdb.d
    entrypoint:
      bash -c "
      echo pg-start
      && export POSTGRES_USER=$$DB_USER
      && export POSTGRES_PASSWORD=$$DB_PASS
      && export POSTGRES_DB=$$DB_NAME
      && docker-entrypoint.sh postgres
      "