version: '3.3'

services:
  pg-0:
    image: postgres:10.5
    env_file:
      - environment.env
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    entrypoint:
      bash -c "
      echo pg-start
      && export POSTGRES_USER=$$DB_USER
      && export POSTGRES_PASSWORD=$$DB_PASS
      && export POSTGRES_DB=$$DB_NAME
      && docker-entrypoint.sh postgres
      "
  pg-1:
    image: postgres:10.5
    env_file:
      - environment.env
    ports:
      - 6432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    entrypoint:
      bash -c "
      echo pg-start
      && export POSTGRES_USER=$$DB_USER
      && export POSTGRES_PASSWORD=$$DB_PASS
      && export POSTGRES_DB=$$DB_NAME
      && docker-entrypoint.sh postgres
      "

  pg-2:
    image: postgres:10.5
    env_file:
      - environment.env
    ports:
      - 7432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    entrypoint:
      bash -c "
      echo pg-start
      && export POSTGRES_USER=$$DB_USER
      && export POSTGRES_PASSWORD=$$DB_PASS
      && export POSTGRES_DB=$$DB_NAME
      && docker-entrypoint.sh postgres
      "